line-length = 93
extend-include = [
    "bin/gemini-status",
    "bin/toml-mdformat",
    "gemini/bin/gemini-sandboxed",
    "scripts/update-ruff-includes",
]

[lint]
select = ["E", "F", "I", "B", "UP", "A", "C4", "SIM", "RUF", "PLC0415", "D1"]
