#!/bin/bash
set -o xtrace
set -o errexit
set -o nounset
set -o pipefail

# Mark the currently edited branch before amending.
current_branch="$(git rev-parse --abbrev-ref HEAD)"
preamend_branch="preamend-$current_branch"
git branch "$preamend_branch" "$current_branch"

# Amend current branch.
git commit --all --amend --no-edit

# gRebase it's child branches.
git amend-fixup

# Checkout back to the current branch.
git checkout "$current_branch"
